
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/folhoso:latest
    
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/folhoso

  build-arm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build
      run: docker buildx build . --platform=linux/arm64 --file ./Dockerfile-arm --tag ${{secrets.DOCKER_USER}}/folhoso-arm:latest

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/folhoso-arm:latest
