on:
  push:
    branches:
      - "release"
name: Create Release

jobs:
    release-on-push:
        runs-on: ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        steps:
            - uses: rymndhng/release-on-push-action@master
              with:
                bump_version_scheme: minor
                use_github_release_notes: true